# Generated by Django 5.1 on 2024-10-16 06:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('marcher', 'Marcher'), ('director', 'Director')], default='marcher', max_length=50)),
                ('instrument', models.CharField(choices=[('n/a', 'N/A'), ('other', 'Other'), ('flute/piccolo', 'Flute/Piccolo'), ('clarinet', 'Clarinet'), ('bass clarinet', 'Bass Clarinet'), ('alto saxophone', 'Alto Saxophone'), ('tenor saxophone', 'Tenor Saxophone'), ('baritone saxophone', 'Baritone Saxophone'), ('trumpet', 'Trumpet'), ('trombone', 'Trombone'), ('baritone/euphonium', 'Baritone/Euphonium'), ('sousaphone', 'Sousaphone'), ('drum line', 'Drum Line')], default='n/a', max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
