# Generated by Django 5.1 on 2024-10-22 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_coordinate', models.FloatField(default=0.0)),
                ('y_coordinate', models.FloatField(default=0.0)),
            ],
        ),
    ]
