# Generated by Django 5.1 on 2024-11-19 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BandField', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordings',
            name='marcher_members',
            field=models.JSONField(default=list),
        ),
    ]
