# Generated by Django 5.1 on 2024-11-19 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BandField', '0004_recordings_marcher_members'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recordings',
            old_name='marcher',
            new_name='director',
        ),
    ]
